# ~/.termux/termux.properties — Termux Hacker Theme
extra-keys = [[ \
'ESC','/','-','HOME','UP','END','PGUP', \
'TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN' \
]]
bell-character=ignore
use-black-ui=true