# ~/.config/starship.toml — Termux Hacker Theme

format = """
[┌───────────────────](bold green)
[│](bold green)$directory$git_branch$git_status
[│](bold green)$python$nodejs$rust
[└─](bold green)$character"""

[directory]
style = "bold green"
truncation_length = 3

[git_branch]
symbol = " "
style = "green"

[git_status]
style = "bold white"

[python]
symbol = " "
style = "bold green"

[nodejs]
symbol = " "
style = "bold green"

[rust]
symbol = " "
style = "bold green"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold white)