# ~/.zshrc — Termux Hacker Theme

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="" # le prompt est entièrement géré par Starship
plugins=(git zsh-autosuggestions zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh
export TERM=xterm-256color
export COLORTERM=truecolor
export BAT_THEME="ansi"

# Couleurs de fichiers
eval "$(dircolors -b ~/.dircolors)" 

# Alias de navigation et d'affichage
alias ls='eza --icons --group-directories-first'
alias ll='eza --icons --long --classify --group-directories-first'
alias la='eza --icons --long --all --group-directories-first'
alias lt='eza --icons --tree --level=2'
alias cat='bat --paging=never --style=numbers,header'
alias grep='rg'

# Effets et bannière
alias matrix='cmatrix -b -C green'
fastfetch

# Prompt
eval "$(starship init zsh)"